uploads = []
outputs = []

[[generated]]
id = "m4a_nRa7IPqn2DlvdgC2H"
uri = "file://artifacts/camisas-del-puerto/public/camisetas/barca-local.png"
type = "image"
title = "generated_image"

[[generated]]
id = "HA5BCrxoCQvzKIYig9FHY"
uri = "file://artifacts/camisas-del-puerto/public/camisetas/barca-visitante.png"
type = "image"
title = "generated_image"

[[generated]]
id = "FVwmXoyce5DQHEj5K7dL-"
uri = "file://artifacts/camisas-del-puerto/public/camisetas/madrid-local.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Qt565GjRsKYD1N_kVYrDF"
uri = "file://artifacts/camisas-del-puerto/public/camisetas/madrid-visitante.png"
type = "image"
title = "generated_image"

[[generated]]
id = "kheuuvsFBhGYEthg7T11r"
uri = "file://artifacts/camisas-del-puerto/public/camisetas/colombia-local.png"
type = "image"
title = "generated_image"
