"""Generate api-gateway/template.yml (SAM REST API) from the swagger spec.

Reads swagger/puerto-shirts.json (produced by scripts/generate-swagger-spec.cjs)
and emits api-gateway/template.yml with one method per documented endpoint plus
CORS, a regional custom domain, an ACM cert and a Route53 record. The app is
UNAUTHENTICATED for now — no Cognito authorizer (the generator is
authorizer-ready: flip REQUIRE_AUTH + add the security scheme later).

Usage:
  python3 scripts/gen_api_template.py
"""
import json
import os

# ── configuration ──────────────────────────────────────────────────────────────
SKIP_PREFIXES = ("/api-docs",)
REQUIRE_AUTH = False                      # public API for now
HTTP_METHODS = ("get", "post", "put", "patch", "delete")
SWAGGER_SOURCE = "swagger/puerto-shirts.json"
DEFAULT_DOMAIN = "api.shirts.jcampos.dev"

I = [""] + ["  " * n for n in range(1, 12)]   # indentation helpers


def ys(v):
    """Quote a YAML string value if it contains special characters."""
    if not isinstance(v, str):
        return str(v)
    specials = (":", "#", "[", "]", "&", "*", "!", "|", ">", "'", '"', "%", "@", "`", "{", "}")
    if any(c in v for c in specials) or v.strip() != v or v in ("true", "false", "null", "yes", "no") or v == "":
        return '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return v


def lambda_uri_sub():
    fn = "puerto-shirts-${Environment}-api-handler"
    return ('"arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/'
            'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:' + fn + '/invocations"')


# ── load spec ───────────────────────────────────────────────────────────────────
root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
spec_path = os.path.join(root_dir, SWAGGER_SOURCE)
if not os.path.exists(spec_path):
    print(f"ERROR: Swagger spec not found at {spec_path}")
    print("Run: node scripts/generate-swagger-spec.cjs")
    raise SystemExit(1)

with open(spec_path, encoding="utf-8") as f:
    spec = json.load(f)

all_paths = {}
for path, path_item in spec.get("paths", {}).items():
    if any(path.startswith(p) for p in SKIP_PREFIXES):
        continue
    methods = {m: path_item[m] for m in HTTP_METHODS if m in path_item}
    if methods:
        all_paths[path] = methods

# ── build YAML ──────────────────────────────────────────────────────────────────
lines = []


def L(s=""):
    lines.append(s)


L("AWSTemplateFormatVersion: '2010-09-09'")
L("Transform: AWS::Serverless-2016-10-31")
L("Description: puerto-shirts API Gateway (generated by scripts/gen_api_template.py)")
L()
L("Parameters:")
L(I[1] + "Environment:")
L(I[2] + "Type: String")
L(I[2] + "Default: dev")
L(I[2] + "AllowedValues: [dev, prod]")
L(I[1] + "HostedZoneId:")
L(I[2] + "Type: String")
L(I[2] + "Description: Route53 Hosted Zone ID (resolved at deploy time)")
L(I[1] + "DomainName:")
L(I[2] + "Type: String")
L(I[2] + f"Default: {DEFAULT_DOMAIN}")
L(I[2] + "Description: Custom domain for the API")
L()
L("Resources:")
L()

# ── API ──────────────────────────────────────────────────────────────────────────
L(I[1] + "ApiGatewayRestApi:")
L(I[2] + "Type: AWS::Serverless::Api")
L(I[2] + "Properties:")
L(I[3] + 'Name: !Sub "puerto-shirts-${Environment}-api"')
L(I[3] + "StageName: !Ref Environment")
L(I[3] + "DefinitionBody:")
L(I[4] + "openapi: '3.0.1'")
L(I[4] + "info:")
L(I[5] + 'title: !Sub "puerto-shirts-${Environment}-api"')
L(I[5] + "description: Camisas del Puerto API")
L(I[5] + "version: '1.0.0'")
L(I[4] + "servers:")
L(I[5] + '- url: !Sub "https://${DomainName}"')
L(I[6] + "x-amazon-apigateway-endpoint-configuration:")
L(I[7] + "disableExecuteApiEndpoint: true")
L(I[4] + "paths:")

for path in sorted(all_paths.keys()):
    methods = all_paths[path]
    allowed_methods = ",".join(m.upper() for m in methods) + ",OPTIONS"

    L(I[5] + ys(path) + ":")

    for method, op in methods.items():
        path_params = [p for p in op.get("parameters", []) if p.get("in") == "path"]
        query_params = [p for p in op.get("parameters", []) if p.get("in") == "query"]
        summary = op.get("summary", "")
        op_id = "puertoshirts_" + (op.get("operationId") or (method + "_" + path.strip("/").replace("/", "_").replace("{", "").replace("}", "")))

        L(I[6] + method + ":")
        L(I[7] + "operationId: " + ys(op_id))
        if summary:
            L(I[7] + "summary: " + ys(summary))
        if path_params or query_params:
            L(I[7] + "parameters:")
            for p in path_params + query_params:
                req = "true" if p.get("required") else "false"
                ptype = (p.get("schema") or {}).get("type", "string")
                L(I[8] + "- name: " + ys(p["name"]))
                L(I[9] + "in: " + p["in"])
                L(I[9] + "required: " + req)
                L(I[9] + "schema:")
                L(I[9] + "  type: " + ptype)
        if method in ("post", "put", "patch"):
            L(I[7] + "requestBody:")
            L(I[8] + "required: true")
            L(I[8] + "content:")
            L(I[9] + "application/json:")
            L(I[10] + "schema:")
            L(I[11] + "type: object")
        L(I[7] + "responses:")
        L(I[8] + "'200':")
        L(I[9] + "description: OK")
        L(I[9] + "headers:")
        L(I[9] + "  Access-Control-Allow-Origin:")
        L(I[9] + "    schema:")
        L(I[9] + "      type: string")
        L(I[7] + "x-amazon-apigateway-integration:")
        L(I[8] + "httpMethod: POST")
        L(I[8] + "uri: !Sub " + lambda_uri_sub())
        L(I[8] + "passthroughBehavior: when_no_match")
        L(I[8] + "contentHandling: CONVERT_TO_TEXT")
        L(I[8] + "type: aws_proxy")

    # OPTIONS (CORS preflight) — mock integration
    L(I[6] + "options:")
    L(I[7] + "responses:")
    L(I[8] + "'200':")
    L(I[9] + "description: CORS OK")
    L(I[9] + "headers:")
    for hdr in ("Access-Control-Allow-Origin", "Access-Control-Allow-Methods", "Access-Control-Allow-Headers"):
        L(I[9] + "  " + hdr + ":")
        L(I[9] + "    schema:")
        L(I[9] + "      type: string")
    L(I[7] + "x-amazon-apigateway-integration:")
    L(I[8] + "type: mock")
    L(I[8] + "requestTemplates:")
    L(I[9] + 'application/json: \'{"statusCode": 200}\'')
    L(I[8] + "responses:")
    L(I[9] + "default:")
    L(I[9] + "  statusCode: '200'")
    L(I[9] + "  responseParameters:")
    L(I[9] + "    method.response.header.Access-Control-Allow-Headers:"
       " \"'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Requested-With'\"")
    L(I[9] + "    method.response.header.Access-Control-Allow-Methods: \"'" + allowed_methods + "'\"")
    L(I[9] + "    method.response.header.Access-Control-Allow-Origin: \"'*'\"")

L()

# ── CORS gateway responses ───────────────────────────────────────────────────────
for rtype in ("DEFAULT_4XX", "DEFAULT_5XX"):
    rname = "GatewayResponse" + rtype.replace("_", "")
    L(I[1] + rname + ":")
    L(I[2] + "Type: AWS::ApiGateway::GatewayResponse")
    L(I[2] + "Properties:")
    L(I[3] + "ResponseParameters:")
    L(I[4] + "gatewayresponse.header.Access-Control-Allow-Headers:"
       " \"'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Requested-With'\"")
    L(I[4] + "gatewayresponse.header.Access-Control-Allow-Methods: \"'GET,POST,PUT,PATCH,DELETE,OPTIONS'\"")
    L(I[4] + "gatewayresponse.header.Access-Control-Allow-Origin: \"'*'\"")
    L(I[3] + "ResponseType: " + rtype)
    L(I[3] + "RestApiId: !Ref ApiGatewayRestApi")
    L()

# ── SSL certificate ──────────────────────────────────────────────────────────────
L(I[1] + "ApiCertificate:")
L(I[2] + "Type: AWS::CertificateManager::Certificate")
L(I[2] + "Properties:")
L(I[3] + "DomainName: !Ref DomainName")
L(I[3] + "ValidationMethod: DNS")
L(I[3] + "DomainValidationOptions:")
L(I[4] + "- DomainName: !Ref DomainName")
L(I[5] + "HostedZoneId: !Ref HostedZoneId")
L()

# ── custom domain (v2) ──────────────────────────────────────────────────────────
L(I[1] + "ApiDomainName:")
L(I[2] + "Type: AWS::ApiGatewayV2::DomainName")
L(I[2] + "Properties:")
L(I[3] + "DomainName: !Ref DomainName")
L(I[3] + "DomainNameConfigurations:")
L(I[4] + "- EndpointType: REGIONAL")
L(I[5] + "CertificateArn: !Ref ApiCertificate")
L()

# ── API mapping (root /) ─────────────────────────────────────────────────────────
L(I[1] + "ApiMapping:")
L(I[2] + "Type: AWS::ApiGatewayV2::ApiMapping")
L(I[2] + "Properties:")
L(I[3] + "ApiId: !Ref ApiGatewayRestApi")
L(I[3] + "DomainName: !Ref ApiDomainName")
L(I[3] + "Stage: !Ref Environment")
L()

# ── Route53 record ───────────────────────────────────────────────────────────────
L(I[1] + "ApiDnsRecord:")
L(I[2] + "Type: AWS::Route53::RecordSet")
L(I[2] + "Properties:")
L(I[3] + "HostedZoneId: !Ref HostedZoneId")
L(I[3] + "Name: !Ref DomainName")
L(I[3] + "Type: A")
L(I[3] + "AliasTarget:")
L(I[4] + "DNSName: !GetAtt ApiDomainName.RegionalDomainName")
L(I[4] + "HostedZoneId: !GetAtt ApiDomainName.RegionalHostedZoneId")
L()

# ── Lambda invoke permission ─────────────────────────────────────────────────────
L(I[1] + "LambdaPermissionBackend:")
L(I[2] + "Type: AWS::Lambda::Permission")
L(I[2] + "Properties:")
L(I[3] + 'FunctionName: !Sub "puerto-shirts-${Environment}-api-handler"')
L(I[3] + "Action: lambda:InvokeFunction")
L(I[3] + "Principal: apigateway.amazonaws.com")
L(I[3] + 'SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestApi}/*"')
L()

# ── Outputs ──────────────────────────────────────────────────────────────────────
L("Outputs:")
L(I[1] + "ApiId:")
L(I[2] + "Value: !Ref ApiGatewayRestApi")
L(I[1] + "ApiEndpoint:")
L(I[2] + 'Value: !Sub "https://${DomainName}"')
L(I[1] + "ApiInvokeUrl:")
L(I[2] + 'Value: !Sub "https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"')

# ── write template ───────────────────────────────────────────────────────────────
out_dir = os.path.join(root_dir, "api-gateway")
os.makedirs(out_dir, exist_ok=True)
out = "\n".join(lines) + "\n"
with open(os.path.join(out_dir, "template.yml"), "w", encoding="utf-8") as f:
    f.write(out)

total_ops = sum(len(m) for m in all_paths.values())
print(f"Generated api-gateway/template.yml  ({len(all_paths)} paths, {total_ops} operations)")

# ── endpoints.json (documentation) ───────────────────────────────────────────────
endpoints = []
for path in sorted(all_paths.keys()):
    for method, op in all_paths[path].items():
        params = op.get("parameters", [])
        endpoints.append({
            "path": path,
            "method": method.upper(),
            "summary": op.get("summary", ""),
            "auth_required": REQUIRE_AUTH,
            "path_params": [p["name"] for p in params if p.get("in") == "path"],
            "query_params": [p["name"] for p in params if p.get("in") == "query"],
        })

endpoints_json = {
    "base_url": f"https://{DEFAULT_DOMAIN}",
    "auth": "none (public)",
    "services": [{"name": "puerto-shirts", "endpoints": endpoints}],
}
with open(os.path.join(out_dir, "endpoints.json"), "w", encoding="utf-8") as f:
    json.dump(endpoints_json, f, ensure_ascii=False, indent=2)
print(f"Generated api-gateway/endpoints.json  ({len(endpoints)} endpoints)")
